### ISSUE TITLE
panic: Init not valid (%d)!

### ISSUE THREAD

**Issue by vivia1990** [mentos-team/MentOS#14]
Ciao,
Installando il sistema come da readme, una volta lanciato `make qemu`, mentos si avvia ma da un errore quando tenta di lanciare il processo init.
Ho messo i livelli di debug dei possibili file sorgente interessati a `loglevel debug`, allego l'output
[`log.txt`](https://github.com/mentos-team/MentOS/files/10231304/log.txt)

Ho provato a riclonare, scaricare il progetto e anche la release 0.50 ma ottengo sempre lo stesso errore.

#### Sistema:
- OS: Arch Linux x86_64
- Kernel: 6.0.10-arch2-1
- gcc: 12.2.0
- qemu: 7.1.0

Fatemi sapere se devo scrivere la issue in inglese.
Grazie mille.

**Comment by vivia1990** [comment]
--Update:
Ho provato con una VM `ubuntu-22.04` e `Qemu 6.2`
Con questo setup non da errore sul filesystem e Mentos si avvia correttamente.
Il problema potrebbe essere di compatibilità con la versione di Qemu?

**Comment by Sirio02** [comment]
> --Update: Ho provato con una VM `ubuntu-22.04` e `Qemu 6.2` Con questo setup non da errore sul filesystem e Mentos si avvia correttamente. Il problema potrebbe essere di compatibilità con la versione di Qemu?

Confermo che con ubuntu-22.04 e QEMU 6.2 MentOS funziona correttamente. 
Su ubuntu-18.04 con QEMU 2.11, invece, mi restituiva il tuo stesso errore nel tentativo di lancio del processo init.

**Comment by vivia1990** [comment]
Penso di aver risolto. Il problema era nella configurazioni di default di mke2fs, relativamente alla dimensione di default dei blocchi. Su arch è settata a 1024 su Ubuntu non è settata quindi usa quella di default ossia 4096. Le configurazioni sono in `/etc/mke2fs.conf` ( non riesco ad allegarle )

Per risolvere quindi basta passare l'opzione `-b 4096` al comando per generare l'immagine.
`mke2fs -L 'rootfs' -b 4096  -d ../files -m 5 -r 1 -t ext2 -v -F rootfs.img 32M`

Fatemi sapere se devo fare una pull request.
Grazie.

**Comment by Galfurian** [comment]
Se riusciamo a risolvere il problema di compatiblità a livello MentOS, meglio ancora.

Se volete, fate tranquillamente un pull request appena avete controllato.

Grazie ancora per il vostro supporto!

**Comment by Galfurian** [comment]
## Answer to OP (ita)

Ho capito cosa succede, la spiegazione completa è qui di seguito. E' forse un problema di come leggo le informazioni dal filesystem. Dopo aver raccolto le informazioni qui sotto, ho l'impressione sia risolvibile.

## Full Details (eng)

I've found the problem, and the problem here is when we try to **read the content of an inode**.

### Inode and data reading

An **inode** is a simple structure that, among other details, tells you where the content/real data associated with it really resides. I'm talking about the `data.blocks` field.
```c
typedef struct ext2_inode_t {
    ...
    union {
        /// [60 byte] Blocks indices.
        struct {
            /// [48 byte]
            uint32_t dir_blocks[EXT2_INDIRECT_BLOCKS];
            /// [ 4 byte]
            uint32_t indir_block;
            /// [ 4 byte]
            uint32_t doubly_indir_block;
            /// [ 4 byte]
            uint32_t trebly_indir_block;
        } blocks;
    } data;
    ...
} ext2_inode_t;
```
Each inode contains 12 (`EXT2_INDIRECT_BLOCKS`) direct pointers, one singly indirect pointer, one doubly indirect block pointer, and one triply indirect pointer.

Apparently, when generating an ext2 with block size `1024`, some of the direct pointers are set to `0`. If I print the direct pointers of the inode associated with `init` (in my case inode 21) I obtain:
```
 0 -> 635
 1 -> 0
 2 -> 0
 3 -> 0
 4 -> 636
 5 -> 637
 6 -> 638
 7 -> 639
 8 -> 640
 9 -> 641
10 -> 642
11 -> 643
```
There is a gap there, at 1, 2, and 3, where the block index is set to 0. So, when it tries to **read the inode data**, and specifically the content of **init** what happens is the following:

 1. `[ext2.c:1494]` It asks to read the `ext2_read_inode_block` with block index `1` of the given `inode`;
 2. `[ext2.c:1418]` The `ext2_read_inode_block` function, asks the real block index associated with `1` with the given `inode`;
 3. `[ext2.c:1313]` Now, 1 is inside the directly addressed blocks (`EXT2_INDIRECT_BLOCKS`), which usually is 12;
 4. `[ext2.c:1314]` It returns the (direct) block index at position `1` which, unfortunately, is `0`.

I have no idea why I have zeros inside the list of directly addressed blocks.

Opening the filesystem with `debugfs` and printing the stat of the init file I have a match with what I'm seeing there:
```
Inode: 21   Type: regular    Mode:  0755   Flags: 0x0
Generation: 0    Version: 0x00000000
User:  1000   Group:  1000   Size: 41424
File ACL: 0
Links: 1   Blockcount: 66
Fragment:  Address: 0    Number: 0    Size: 0
ctime: 0x63a04897 -- Mon Dec 19 12:18:47 2022
atime: 0x63a04b9e -- Mon Dec 19 12:31:42 2022
mtime: 0x63a04897 -- Mon Dec 19 12:18:47 2022
BLOCKS:
(0):635, (4-11):636-643, (IND):644, (12-24):645-657, (28-32):658-662, (36-40):663-667
TOTAL: 33
```
So, there is actually a gap there `(0):635, (4-11):636-643`, I probably need to skip the entries with zeros...

### Possible solution
I think the problem resides where I read the inode content, at `ext2_read_inode_data`. Specifically, when we try to read multiple blocks, i.e., the starting and ending blocks are not the same `start_block != end_block`.
The code that should be modified goes from `[ext2.c:1486]` to `[ext2.c:1509]`.
```
        for (block_offset = start_block; block_offset < end_block; block_offset++, blocks_read++) {
            // Read the real block.
            if (ext2_read_inode_block(fs, inode, block_offset, cache) == -1) {
```
I should probably improve the error handling of `ext2_read_inode_block` and return the actual content of the direct block pointer list. As such, if `ext2_read_inode_block` returns a `0` I just skip the entry.

**Comment by Galfurian** [comment]
Yes, the fix works. But I need to dig deeper before calling it a **correct** fix.

**Comment by Galfurian** [comment]
The fix I made works.
