### ISSUE TITLE
Panic on boot

### ISSUE THREAD

**Issue by hello01-debug** [mentos-team/MentOS#3]
I ran 
```
cmake ..
make -j2
make qemu
```
I had to remove the ```-sdl``` option because of an error. However, on boot, I get:
```
Assertion `next && "No valid task selected. Have you implemented a scheduling algorithm?"` failed.
```

**Comment by mircodemarchi** [comment]
The kernel panic that you see on boot is expected, because there is no scheduler algorithm implemented by default in MentOS. 

MentOS is an educational operating system that has the aim to approach the students to operating system programming. In fact MentOS has no scheduler algorithm implemented by default, because we want that you learn how scheduler works and implement the algorithm in MentOS. 

Look at the slides linked in our [website](https://mentos-team.github.io/MentOS/), in particular take a look in the [process management](https://mentos-team.github.io/MentOS/doc/process_management.pdf) part. There is explained in a few steps how to implement a simple scheduler algorithm: Round Robin. Have fun!

Instead, about the `-sdl` option, we are working for a MentOS release that improve the compatibility with the last ubuntu and gcc upgrades. The issue has been fixed in https://github.com/mentos-team/MentOS/tree/compatibility branch.

Just clone the repository and checkout in compatibility branch. Soon there will be a release, but for the moment use the compatibility branch.

```
git clone https://github.com/mentos-team/MentOS.git
git checkout compatibility
# ... then the same commands
```

Let us know if everything works as expected.
