### ISSUE TITLE
Booting on Bare Metal

### ISSUE THREAD

**Issue by google0101-ryan** [mentos-team/MentOS#5]
I recently figured out how to load the kernel and initramfs using GRUB. But, I ran into a few issues.
1.) When booting, GRUB complains about me not loading the kernel first, but I have the multiboot command before the initrd command.

2.) The username root and the password password do not work. It simply says, sorry, try again. This happens with user and computer as well.

Other than this, it works as I would expect. This is an amazing system! Thanks!

**Comment by mircodemarchi** [comment]
I suggest to run MentOS i386 elf image with qemu-system-i386, because GRUB can't manage the currently implemented filesystem and it builds a ISO image without the filesystem. We have tested MentOS with the i386 elf image, then surely this works well. You can use the command `make qemu` to test MentOS.

Unfortunately MentOS support a dummy filesystem, built by initfs script on the main memory of the system. In fact the filesystem is not permanent. GRUB is able to load the MentOS kernel and build a MentOS ISO image, but it fails during the filesystem initialization, because it's not able to load the filesystem in the ISO image. Since that the login user and password are saved in filesystem, you can't login because MentOS is not able to find the filesystem.

We are working on elf3 and elf4 linux-like filesystem, but for the moment a release is not planned in a short time.

I'm glad you enjoy MentOS! Thank you for your feedbacks.

**Comment by lotation** [comment]
Are there any updates?

**Comment by Galfurian** [comment]
Sorry for the late reply.

Just yesterday @rouseabout pushed some changes that should help fix the compatibility of MentOs with GRUB. In the next couple of months, I will try to look into this matter, and prepare both documentation and a branch for further testing.

I'm not sure if the changes I made in the **develop** branch, will disrupt even further the objective (compatibility with GRUB). Because there (in **develop**), I worked on supporting **ext2** filesystems and completed the task. However, this changed the overall structure of the OS, there is no **initramfs** anymore, and everything is inside the **ext2** filesystem. Anyway, maybe this will not cause any trouble, but... I'm always preparing for the worst.

**Comment by Galfurian** [comment]
Inside the development branch, I created the `qemu-grub` target and tested it out.

So basically, we do not have an **initramfs** filesystem anymore, we just have the **kernel image** and the **ext2** filesystem. Because of that, the cdrom contains only the **kernel image** and the `grub.cfg` file.

I tested it out and it works, at least on **ubuntu** using **qemu**, I did not try to create a bootable USB and run with it.
